-- MySQL Script generated by MySQL Workbench
-- 09/12/17 15:29:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Vuelos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vuelos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vuelos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `Vuelos` ;

-- -----------------------------------------------------
-- Table `Vuelos`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`CLIENT` (
  `id_CLIENT` INT NOT NULL COMMENT '',
  `name_CLIENT` VARCHAR(45) NOT NULL COMMENT '',
  `lastname_CLIENT` VARCHAR(45) NOT NULL COMMENT '',
  `direction_CLIENT` VARCHAR(45) NULL COMMENT '',
  `tel_CLIENT` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_CLIENT`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`AIRPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`AIRPORT` (
  `id_AIRPORT` VARCHAR(6) NOT NULL COMMENT '',
  `name_AIRPORT` INT NOT NULL COMMENT '',
  `city_AIRPORT` VARCHAR(45) NOT NULL COMMENT '',
  `country_AIRPORT` VARCHAR(45) NOT NULL COMMENT '',
  `fly_CODE` VARCHAR(45) NOT NULL COMMENT '',
  `id_SEATING` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_AIRPORT`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`FLYES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`FLYES` (
  `id_FLYES` INT NOT NULL COMMENT '',
  `exit_DATE` DATE NOT NULL COMMENT '',
  `exit_HOUR` TIME(4) NOT NULL COMMENT '',
  `arrival_DATE` DATE NOT NULL COMMENT '',
  `arrival_HOUR` TIME(4) NOT NULL COMMENT '',
  `AIRPORT_id_AIRPORT` VARCHAR(6) NOT NULL COMMENT '',
  PRIMARY KEY (`id_FLYES`)  COMMENT '',
  INDEX `fk_FLYES_AIRPORT1_idx` (`AIRPORT_id_AIRPORT` ASC)  COMMENT '',
  CONSTRAINT `fk_FLYES_AIRPORT1`
    FOREIGN KEY (`AIRPORT_id_AIRPORT`)
    REFERENCES `Vuelos`.`AIRPORT` (`id_AIRPORT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`RESERVATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`RESERVATION` (
  `id_RESERVATION` INT NOT NULL COMMENT '',
  `DESTINITY` VARCHAR(45) NOT NULL COMMENT '',
  `AIRLINE` VARCHAR(45) NOT NULL COMMENT '',
  `CLIENT_id_CLIENT` INT NOT NULL COMMENT '',
  `FLYES_id_FLYES` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_RESERVATION`)  COMMENT '',
  INDEX `fk_RESERVATION_CLIENT_idx` (`CLIENT_id_CLIENT` ASC)  COMMENT '',
  INDEX `fk_RESERVATION_FLYES1_idx` (`FLYES_id_FLYES` ASC)  COMMENT '',
  CONSTRAINT `fk_RESERVATION_CLIENT`
    FOREIGN KEY (`CLIENT_id_CLIENT`)
    REFERENCES `Vuelos`.`CLIENT` (`id_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_FLYES1`
    FOREIGN KEY (`FLYES_id_FLYES`)
    REFERENCES `Vuelos`.`FLYES` (`id_FLYES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`TICKET` (
  `id_TICKET` INT NOT NULL COMMENT '',
  `lastname_CLIENT` VARCHAR(45) NOT NULL COMMENT '',
  `name_CLIENT` VARCHAR(45) NOT NULL COMMENT '',
  `direction_CLIENT` INT NOT NULL COMMENT '',
  `tel_CLIENT` VARCHAR(45) NOT NULL COMMENT '',
  `RESERVATION_id_RESERVATION` INT NOT NULL COMMENT '',
  `CLIENT_id_CLIENT` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_TICKET`)  COMMENT '',
  INDEX `fk_TICKET_RESERVATION1_idx` (`RESERVATION_id_RESERVATION` ASC)  COMMENT '',
  INDEX `fk_TICKET_CLIENT1_idx` (`CLIENT_id_CLIENT` ASC)  COMMENT '',
  CONSTRAINT `fk_TICKET_RESERVATION1`
    FOREIGN KEY (`RESERVATION_id_RESERVATION`)
    REFERENCES `Vuelos`.`RESERVATION` (`id_RESERVATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKET_CLIENT1`
    FOREIGN KEY (`CLIENT_id_CLIENT`)
    REFERENCES `Vuelos`.`CLIENT` (`id_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`SEATING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`SEATING` (
  `id_SEATING` VARCHAR(45) NOT NULL COMMENT '',
  `id_PLANE` VARCHAR(45) NOT NULL COMMENT '',
  `door_SHIPMENT` INT NULL COMMENT '',
  `seating_FREE` INT NULL COMMENT '',
  `seating_RESERVED` INT NULL COMMENT '',
  `FLOOR` INT NULL COMMENT '',
  `exit_HOUR` TIME(4) NOT NULL COMMENT '',
  `exit_DATE` DATE NOT NULL COMMENT '',
  `n°_SEATING` INT NOT NULL COMMENT '',
  `FLYES_id_FLYES` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_SEATING`)  COMMENT '',
  INDEX `fk_SEATING_FLYES1_idx` (`FLYES_id_FLYES` ASC)  COMMENT '',
  CONSTRAINT `fk_SEATING_FLYES1`
    FOREIGN KEY (`FLYES_id_FLYES`)
    REFERENCES `Vuelos`.`FLYES` (`id_FLYES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vuelos`.`AIRPLANE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vuelos`.`AIRPLANE` (
  `id_AIRPLANE` VARCHAR(45) NOT NULL COMMENT '',
  `SEATING_id_SEATING` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_AIRPLANE`)  COMMENT '',
  INDEX `fk_AIRPLANE_SEATING1_idx` (`SEATING_id_SEATING` ASC)  COMMENT '',
  CONSTRAINT `fk_AIRPLANE_SEATING1`
    FOREIGN KEY (`SEATING_id_SEATING`)
    REFERENCES `Vuelos`.`SEATING` (`id_SEATING`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
